---
title: "Appendix"
output:
  pdf_document:
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
```

```{r read_chunks, cache=FALSE, echo=FALSE}
knitr::read_chunk("../scripts/99_utils.R")
```

```{r source_utils, message=FALSE, results='hide', echo=FALSE, warning=FALSE}

```

```{r load_data, message=FALSE, results='hide', echo=FALSE, warning=FALSE}
  if(file.exists("../scripts/01.5_loaddata.R")){
    source("../scripts/01.5_loaddata.R")  
  }else{
    source("scripts/01.5_loaddata.R")  
  }
```

```{r recursive_partitioning_viz, echo=FALSE, eval=FALSE}
plot_tree(gettree(readRDS("../data/maxdepth_forest.rds")), 
          title = "Max Depth")

plot_tree(gettree(readRDS("../data/iws/cd_forest.rds")), 
          title = "Distance to Closest \n Upstream Lake (standardized)")
# inv_inv_closest(-1.51, nes_rf_iws) # 3773.614
plot_tree(gettree(readRDS("../data/nws/cd_forest.rds")), 
          title = "Distance to Closest \n Upstream Lake (standardized)")
# inv_inv_closest(-1.469, nes_rf_nws) # 2681.288

plot_tree(gettree(readRDS("../data/iws/sr_forest.rds")), 
          title = "Stream Order Ratio")
plot_tree(gettree(readRDS("../data/nws/sr_forest.rds")), 
          title = "Stream Order Ratio")

plot_tree(gettree(readRDS("../data/iws/linklength_forest.rds")), 
          title = "Link Length")
plot_tree(gettree(readRDS("../data/nws/linklength_forest.rds")), 
          title = "Link Length")

plot_tree(gettree(readRDS("../data/iws/uplakearea_forest.rds")), 
          title = "Upstream Lake Area")
# plot_tree(gettree(readRDS("01_Chapter/data/nws/uplakearea_forest.rds")), 
#           title = "Upstream Lake Area")

plot_tree(gettree(readRDS("../data/iws/baseflow_forest.rds")), 
          title = "Baseflow")

plot_tree(gettree(readRDS("../data/iws/wetland-cover_forest.rds")), 
          title = "Wetland Cover")

plot_tree(gettree(readRDS("../data/iws/streamdensity_forest.rds")), 
          title = "Stream Density")
```

```{r graphical_exploratory_analysis, echo=FALSE, message=FALSE, warning=FALSE, fig.height=8.4, fig.cap="Exploratory plots"}
partition_splits <- read.csv("../figures/table_1.csv", stringsAsFactors = FALSE)

nes_iws$p_pnt_source <-  rowSums(cbind(nes_iws$p_pnt_source_muni,
                                       nes_iws$p_pnt_source_septic,
                                       nes_iws$p_pnt_source_industrial),
                                 na.rm = TRUE)

md_v_la <- ggplot(data = nes_iws) + 
  geom_point(aes(x = maxdepth, 
                 y = upstream_lakes_4ha_area_ha, color = lakeconnection)) +
  ylab("Upstream Lake Area (ha)") + xlab("Max Depth (m)") + 
  geom_vline(data = partition_splits, aes(
    xintercept = partition_splits$splits[
      partition_splits$pnames2 == "md" & partition_splits$scale == "focal"])) + 
  geom_hline(data = partition_splits, aes(
    yintercept = partition_splits$splits[
      partition_splits$pnames2 == "la" & partition_splits$scale == "nws"])) + 
  scale_y_log10()

md_v_ll_iws <- ggplot(data = nes_iws) + 
  geom_point(aes(x = maxdepth, 
                 y = link_length, color = lakeconnection)) +
  ylab("Link Length") + xlab("Max Depth (m)") + 
  geom_vline(data = partition_splits, aes(
    xintercept = partition_splits$splits[
      partition_splits$pnames2 == "md"])) + 
  geom_hline(data = partition_splits, aes(
    yintercept = partition_splits$splits[
      partition_splits$pnames2 == "ll" & partition_splits$scale == "iws"]))

md_v_ll_nws <- ggplot(data = nes_nws) + 
  geom_point(aes(x = maxdepth, 
                 y = avg_link_length, color = lakeconnection)) +
  ylab("Link Length") + xlab("Max Depth (m)") + 
  geom_vline(data = partition_splits, aes(
    xintercept = partition_splits$splits[
      partition_splits$pnames2 == "md"])) + 
  geom_hline(data = partition_splits, aes(
    yintercept = partition_splits$splits[
      partition_splits$pnames2 == "ll" & partition_splits$scale == "nws"]))

md_v_cd_nws <- ggplot(data = nes_nws) + 
  geom_point(aes(x = maxdepth, 
                 y = closest_lake_distance, color = lakeconnection)) +
  ylab("Closest Lake Distance") + xlab("Max Depth (m)") + 
  geom_vline(data = partition_splits, aes(
    xintercept = partition_splits$splits[
      partition_splits$pnames2 == "md"])) + 
  geom_hline(data = partition_splits, aes(
    yintercept = partition_splits$splits[
      partition_splits$pnames2 == "cd" & partition_splits$scale == "nws"]))

ll_v_cd_nws <- ggplot(data = nes_nws) + 
  geom_point(aes(x = avg_link_length, 
                 y = closest_lake_distance, color = lakeconnection)) +
  ylab("Closest Lake Distance") + xlab("Link Length") + 
  geom_vline(data = partition_splits, aes(
    xintercept = partition_splits$splits[
      partition_splits$pnames2 == "ll" & partition_splits$scale == "nws"])) + 
  geom_hline(data = partition_splits, aes(
    yintercept = partition_splits$splits[
      partition_splits$pnames2 == "cd" & partition_splits$scale == "nws"])) + 
  scale_x_log10() + scale_y_log10() + xlab("log(Link Length)") + ylab("log(cd)")

legend <- get_legend(md_v_la)

plot_grid(md_v_la + theme(legend.position = "none"), 
          md_v_ll_iws + theme(legend.position = "none"), 
          md_v_ll_nws + theme(legend.position = "none"),
          ll_v_cd_nws + theme(legend.position = "none"),
          ggplot() + geom_point(aes(nes_iws$hu12_baseflowindex_mean, nes_nws$baseflow, color = nes_iws$state %in% c("MAINE", "NEW HAMPSHIRE", "IOWA", "MISSOURI", "OHIO", "ILLINOIS"))) + 
            geom_hline(aes(yintercept = 53.43)) +
            geom_vline(aes(xintercept = 63.76)) + 
            ylab("NWS Baseflow") + xlab("IWS Baseflow") + 
            theme(legend.position = "none"),
          ggplot() + geom_point(aes(
            nes_iws$iws_streamdensity_streams_density_mperha, 
            nes_nws$stream_density, color = nes_iws$lakeconnection)) + 
            geom_hline(aes(yintercept = 10.4), color = "red") +
            geom_vline(aes(xintercept = 4.43), color = "red") +
            geom_abline(aes(slope = 1, intercept = 0)) + 
            ylab("NWS Stream Density") + xlab("IWS Stream Density") + 
            theme(legend.position = "none"),
          
          ggplot() + geom_point(aes(nes_iws$closest_lake_distance, 
                                    nes_nws$closest_lake_distance, 
                                    color = nes_iws$lakeconnection)) + 
            geom_hline(aes(yintercept = 2776.81), color = "red") +
            geom_vline(aes(xintercept = 3773.61), color = "red") +
            geom_abline(aes(slope = 1, intercept = 0)) +
            scale_x_log10() + 
            scale_y_log10() + 
            ylab("NWS Lake Distance") + xlab("IWS Lake Distance") + 
            theme(legend.position = "none"),
          ggplot(data = nes_iws) + 
            geom_point(aes(x = p_pnt_source / (p_nonpnt_source + p_pnt_source), 
                           y = p_percent_retention)) + 
            xlab("p_percent_pnt-source"), 
          ncol = 2)
```

```{r graphical_exploratory_analysis_cont, echo=FALSE, message=FALSE, warning=FALSE, fig.height=6.3, fig.cap="Exploratory plots cont"}
lg <- lagosne_load("1.087.1")
nes_nws_temp <- dplyr::left_join(nes_nws, select(lg$iws, lagoslakeid, iws_ha))
nes_nws_temp$p_pnt_source <-  rowSums(cbind(nes_nws_temp$p_pnt_source_muni,
                                       nes_nws_temp$p_pnt_source_septic,
                                       nes_nws_temp$p_pnt_source_industrial),
                                 na.rm = TRUE)
nes_nws_sf    <- coordinatize(nes_nws_temp, "lat", "long")
us_states <- st_intersects(us_states(), nes_nws_sf)
us_states <- us_states()[unlist(lapply(us_states, function(x) length(x) > 0)),]

plot_grid(
ggplot() + geom_point(data = nes_nws_temp, 
                      aes(x = iws_ha, y = avg_link_length)) + 
  xlim(300, 100000) + ylab("Average Link Length") + 
  xlab("Interlake Watershed Area (ha)") + 
  geom_hline(aes(yintercept = 2380.09), color = "red"),

ggplot() + geom_point(data = nes_nws_temp, 
                      aes(x = iws_ha, y = closest_lake_distance)) + 
  xlim(300, 100000) + ylab("Closest Lake Distance") + 
  xlab("Interlake Watershed Area (ha)") + 
  geom_hline(aes(yintercept = 3273.65), color = "red"), 

ggplot() + geom_point(data = nes_nws_temp, 
                      aes(x = iws_ha, y = p_percent_retention)) + 
  xlim(300, 100000) + ylab("P Retention") + 
  xlab("Interlake Watershed Area (ha)"),

ggplot() + geom_sf(data = us_states) + 
  geom_sf(data = nes_nws_sf, aes(color = p_pnt_source / (p_nonpnt_source + p_pnt_source))) + theme(legend.direction = "horizontal", legend.position = "bottom") + ggtitle("% pnt source P"),

ggplot() + geom_sf(data = us_states) + 
  geom_sf(data = nes_nws_sf, aes(color = log(maxdepth))) + theme(legend.direction = "horizontal", legend.position = "bottom") + ggtitle("max depth"), 
ggplot() + geom_sf(data = us_states) + 
  geom_sf(data = nes_nws_sf, aes(color = log(iws_ha))) + theme(legend.direction = "horizontal", legend.position = "bottom") + ggtitle("iws area"), 
ncol = 2)
```

```{r graphical_exploratory_analysis_cont_cont, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5.3, fig.cap="Exploratory plots cont x 2"}
lg <- lagosne_load("1.087.1")

nes_nws_temp <- nes_nws
nes_nws_temp$p_pnt_source <-  rowSums(cbind(nes_nws_temp$p_pnt_source_muni,
                                            nes_nws_temp$p_pnt_source_septic,
                                            nes_nws_temp$p_pnt_source_industrial),
                                      na.rm = TRUE)
nes_nws_sf    <- coordinatize(nes_nws_temp, "lat", "long")
us_states <- st_intersects(us_states(), nes_nws_sf)
us_states <- us_states()[unlist(lapply(us_states, function(x) length(x) > 0)),]

plot_grid(
  ggplot() + geom_point(data = nes_nws_temp, 
                        aes(x = nws_ha, y = upstream_lakes_4ha_area_ha)) + 
    xlim(300, 100000) + ylab("Up. Lk. Area") + 
    xlab("Network Watershed Area (ha)"),
  ggplot() + geom_point(data = nes_nws_temp, 
                        aes(x = nws_ha, y = stream_order_ratio)) + 
    xlim(300, 100000) + ylab("Stream Order Ratio") + 
    xlab("Network Watershed Area (ha)"), 
  
  ggplot() + geom_point(data = nes_nws_temp, 
                        aes(x = nws_ha, y = p_percent_retention)) + 
    xlim(300, 100000) + ylab("P Retention") + 
    xlab("Network Watershed Area (ha)"),
  
  ggplot() + geom_point(data = nes_nws_temp, 
                        aes(x = nws_ha, 
                            y = p_pnt_source / (p_nonpnt_source + p_pnt_source))) + 
    xlim(300, 100000) + ylab("% Pnt Source") + 
    xlab("Network Watershed Area (ha)"), 
  ncol = 2)
```

```{r stream_density-vs-link_length}
test <- dplyr::select(nes_nws, 
              avg_link_length, 
              stream_density, 
              closest_lake_distance) %>%
dplyr::rename("Average Link Length" = avg_link_length,
              "Stream Density" = stream_density,
              "Closest Lake Distance" = closest_lake_distance) %>%
dplyr::mutate(`Closest Lake Distance` = `Closest Lake Distance` / 100, 
              `Average Link Length` = `Average Link Length` / 100)

pair_opts <- theme(axis.text = element_blank(), 
      axis.ticks = element_blank())

cowplot::plot_grid(
  ggplot(data = test) + 
    geom_point(aes(y = `Average Link Length`, x = `Stream Density`)) + 
    pair_opts,
  ggplot(data = test) + 
    geom_point(aes(y = `Average Link Length`, x = `Closest Lake Distance`)) + 
    ylab("") + pair_opts, 
  ggplot(data = test) + 
    geom_point(aes(y = `Closest Lake Distance`, x = `Stream Density`)) +
    pair_opts,
  ggplot() + geom_blank(),
  nrow = 2, ncol = 2)
```

```{r conceptual_summary, echo=FALSE, fig.cap="Connectivity metric effects on lake processing.", eval=FALSE}
dt <- data.frame(
  rbind(
    c("closest lake distance", "lower", "higher", "lower", "higher", "lake-stream", "long"), 
    c("average link length", "lower", "higher", "lower", "higher", "stream", "long"), 
    c("lakeconnection", "DR_Stream", "higher", "lower", "higher", "lake", "long"), 
    c("upstream lake area", "lower", "higher", "lower", "higher", "lake", "lat"), 
    c("stream density", "higher", "higher", "lower", "higher", "stream", "lat"),
    c("baseflow", "higher", "higher", "lower", "higher", "stream", "lat"), 
    c("stream order ratio", "higher", "higher", "lower", "higher", "stream", "long")))

names(dt) <- c("metric", "direction", "k", "connectivity", "in_lake_processing", "axis", "connectivity type")

knitr::kable(dt)
```

```{r read_metric_chunks, cache=FALSE, echo=FALSE}
knitr::read_chunk("../data/connectivity_metrics.R")
```

```{r load_packages}

```

```{r source_functions}

```

```{r iws_vs_nws-gis, cache = TRUE}
lagoslakeid <- 6302
iws <- pull_iws(lagoslakeid, maxsteps = Inf)
nws <- pull_nws(lagoslakeid, maxsteps = Inf)

library(rayshader)
library(elevatr)
library(raster)

test <- elevatr::get_elev_raster(as_Spatial(iws), z = 1)




```

```{r best_partition_maps}
partition_splits <- read.csv("../figures/table_1.csv")
partition_splits <- dplyr::filter(partition_splits, !is.na(splits), 
                                  scale %in% c("nws", "iws"))
partition_splits <- droplevels(partition_splits)
partition_splits$pnames2 <- factor(partition_splits$pnames2, 
                              levels = c("cd", "ll", "la", "sd", "bf", "sr"))

nes_sf    <- coordinatize(nes_nws, "lat", "long")
us_states <- st_intersects(us_states(), nes_sf)
us_states <- us_states()[unlist(lapply(us_states, function(x) length(x) > 0)),]

# pull the lower partition group as an sf object
get_sub <- function(dt, col_name, split_value){
  coordinatize(
    dplyr::filter(dt, UQ(rlang::sym(as.character(col_name))) <= split_value), 
    "lat", "long")
}

lower_iws_maps <- lapply(which(partition_splits$scale == "iws"), 
                         function(x) {
                           nes_sub <- get_sub(nes_iws, 
                                            partition_splits[x, "iws_names"],
                                            partition_splits[x, "splits"])
                           
                           ggplot() + 
                             geom_sf(data = us_states) +
                             geom_sf(data = nes_sf, 
                                     color = viridis::viridis(1, begin = 0),
                                     size = 0.6) + 
                             geom_sf(data = nes_sub, 
                                color = viridis::viridis(1, begin = 0.5), 
                                size = 0.6) + 
                             coord_sf(datum = NA) + 
                             ggtitle(break_word(partition_splits[x, "abb"], 12)) + 
                             theme(plot.margin = unit(c(0, -0.1, 0, -0.1), "cm"),
                               plot.title = element_text(face = "plain", size = 12))
                         })

lower_nws_maps <- lapply(which(partition_splits$scale == "nws"), 
                         function(x) {
                           nes_sub <- get_sub(nes_nws, 
                                              partition_splits[x, "nws_names"],
                                              partition_splits[x, "splits"])
                           
                           nes_sf_temp <- nes_sf
                           st_geometry(nes_sf_temp) <- NULL
                           na_rows <- !is.na(
                    nes_sf_temp[,as.character(partition_splits[x, "nws_names"])])
                           
                           ggplot() + 
                             geom_sf(data = us_states) +
                             geom_sf(data = nes_sf, 
                                     color = viridis::viridis(1, begin = 0),
                                     size = 0.6) + 
                             geom_sf(data = nes_sub,
                                     color = viridis::viridis(1, begin = 0.5), 
                                     size = 0.6) + 
                             coord_sf(datum = NA) + 
                             ggtitle(break_word(partition_splits[x, "abb"], 12)) + 
                             theme(plot.margin = unit(c(0, -0.1, 0, -0.1), "cm"), 
                               plot.title = element_text(face = "plain", size  = 12))
                         })

lower_iws_maps <- lower_iws_maps[
  match(levels(partition_splits$pnames2), 
        partition_splits$pnames2[which(partition_splits$scale == "iws")])
  ]

# lower_iws_maps[1][[1]] <- lower_iws_maps[1][[1]] + 
#   theme(plot.margin = unit(c(1,0,0,0), "lines"))

lower_nws_maps <- lower_nws_maps[
  match(levels(partition_splits$pnames2), 
        partition_splits$pnames2[which(partition_splits$scale == "nws")])
  ]

plot_grid(
  plot_grid(NULL,
            NULL, 
            NULL,
            NULL,
            NULL, 
            nrow = 4, ncol = 1,
            labels = c("A. LWS", "", "B. NWS", "", ""), 
            label_colour = "black", vjust = c(1.2, 0, 2, 0, 0), 
            hjust = c(-0.1, 0, -0.12, 0, 0)),
  plot_grid(
    plot_grid(plotlist = lower_iws_maps, 
                   ncol = 3, nrow = 2, align = "v"),
    plot_grid(ggplot() + geom_blank()),
    plot_grid(plotlist = lower_nws_maps,
                   ncol = 3, nrow = 2, align = "v"), 
    ncol = 1, rel_heights = c(1, 0.1, 1)), 
rel_widths = c(0.2, 1), ncol = 2)

```