---
title: "Figures"
output:
  pdf_document:
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
```

```{r read_chunks, cache=FALSE, echo=FALSE}
# knitr::read_chunk("../scripts/03_viz.R")
knitr::read_chunk("../scripts/99_utils.R")
```

```{r source_utils, message=FALSE, results='hide', echo=FALSE, warning=FALSE}
# setwd("scripts")
# source("99_utils.R")
```

```{r load_data, message=FALSE, results='hide', echo=FALSE, warning=FALSE}
  source("../scripts/01.5_loaddata.R")
```

```{r 06_k, echo=FALSE, message=FALSE, fig.cap="Distribution of the k parameter from the Vollenweider equation in low and high connectivity partitions at the (A) lake watershed and (B) network watershed scales. Green symbols indicate the lower of the two partition groups while purple symbols represent the higher of the two partition groups (see Table 2).", fig.width=7, fig.height=3.8, warning=FALSE}

model_signif <- read.csv("../scripts/model_signif.csv", 
                         stringsAsFactors = FALSE)

fit_df_iws <- rbind(
  extract_coefs(readRDS("../data/global_vollenweider.rds"), "k"), 
  extract_coefs2(readRDS("../data/lc_vollenweider.rds"), 
                 c("k1_lc", "k2_lc")),
  extract_coefs2(readRDS("../data/md_vollenweider.rds"), 
                 c("k1_md", "k2_md")),
  extract_coefs2(readRDS("../data/iws/la_vollenweider.rds"),
                 c("k1_la", "k2_la")),
  extract_coefs2(readRDS("../data/iws/cd_vollenweider.rds"),
                 c("k1_cd", "k2_cd")),
  extract_coefs2(readRDS("../data/iws/ll_vollenweider.rds"),
                 c("k1_ll", "k2_ll")),
  extract_coefs2(readRDS("../data/iws/bf_vollenweider.rds"),
                 c("k1_bf", "k2_bf")),
  extract_coefs2(readRDS("../data/iws/sd_vollenweider.rds"),
                 c("k1_sd", "k2_sd")),
  extract_coefs2(readRDS("../data/iws/sr_vollenweider.rds"), 
                 c("k1_sr", "k2_sr")))
  #               extract_coefs2(fit_wc, c("k1_wc", "k2_wc")), 

# controls ordering of ridge plot
fit_df_iws$key <- factor(fit_df_iws$key, levels = c("k",
                                                    "k1_sr", "k2_sr",
                                                    "k1_bf", "k2_bf",
                                                    "k2_md", "k1_md",
                                                    "k1_la", "k2_la",
                                                    "k2_lc", "k1_lc",
                                                    "k2_sd", "k1_sd",
                                                    "k1_cd", "k2_cd",
                                                    "k1_ll", "k2_ll"))
# k2  = higher metric value
# right = higher connectivity, purple

iws_labels_raw <- data.frame(parameter = rev(c(
                   "Link length",
                   "Closest lake distance",
                   "Stream density",
                   "Lake connection", 
                   "Upstream lake area",
                   "Max depth",
                   "Baseflow",
                   "Stream order ratio",
                   "Global")), stringsAsFactors = FALSE) %>%
  mutate(parameter_alt = parameter)
iws_labels_raw$parameter_alt[iws_labels_raw$parameter == "Link length"] <- 
  "Average link length"

colorado <- function(src) {
  # https://stackoverflow.com/a/39695859/3362993
  src_levels <- src                                 # retrieve the levels in their order
  boulder <- src_levels[grep("\\*", src_levels)]
  brave <- seq_len(length(src_levels)) %in% grep("\\*", src_levels)                       # make sure everything we want to make bold is actually in the factor levels
  b_pos <- purrr::map_int(boulder, ~which(.==src_levels)) # then find out where they are
  b_vec <- rep("plain", length(src_levels))               # make'm all plain first
  b_vec[b_pos] <- "bold"                                  # make our targets bold
  b_vec                                                   # return the new vector
}

iws_labels <- left_join(iws_labels_raw, model_signif, 
                        by = c("parameter_alt" = "parameter")) %>%
  filter(scale == "iws" | is.na(scale)) %>%
  arrange(match(parameter, iws_labels_raw$parameter)) %>%
  mutate(signif = sapply(signif, signif_star)) %>%
  mutate(parameter = paste0(parameter, signif)) %>%
  select(parameter)

nws_labels <- left_join(iws_labels_raw, model_signif, 
                        by = c("parameter_alt" = "parameter")) %>%
  filter(scale == "nws" | is.na(scale)) %>%
  arrange(match(parameter, iws_labels_raw$parameter)) %>%
  mutate(signif = sapply(signif, signif_star)) %>%
  mutate(parameter = paste0(parameter, signif)) %>%
  select(parameter)

k_viz_iws <- ggplot(
  fit_df_iws, 
  aes(x = coef, y = key, fill = key, color = key)) + 
    geom_density_ridges(size = 0.1, scale = 0.7, rel_min_height = 0.01) + 
    geom_hline(yintercept = seq(1.8, 16.8, by = 2)) +
    scale_fill_manual(values = c("grey", 
                            rep(c(viridis::viridis(1, begin = 0.5), 
                                  viridis::viridis(1, begin = 0)), 8))) +
    scale_color_manual(values = c("grey", 
                               rep(c(viridis::viridis(1, begin = 0.5), 
                                     viridis::viridis(1, begin = 0)), 8))) +
    cowplot::theme_cowplot() + theme(panel.grid.major.y = element_blank(),
                                     axis.text = element_text(size = 9),
                                     axis.text.y = element_text(size = 8, 
                                                face = colorado(iws_labels$parameter)),
                                     axis.title = element_text(size = 10),
                               plot.title = element_text(size = 9, face = "bold", hjust = 0),
                                     axis.line.x = element_line(size = 1, 
                                     colour = "black"),
                                     axis.line.y = element_line(size = 1, 
                                                       colour = "black"), 
                                     legend.position = "none", 
                                     plot.margin = margin(0.5,0,0,0, "cm")) + 
  xlab("k Value") + ylab("") + 
  scale_y_discrete(breaks = levels(fit_df_iws$key)[
    c(1, seq(3, length(levels(fit_df_iws$key)), by = 2))], 
                   labels = iws_labels$parameter)

k_viz_iws

fit_df_nws <- rbind(
  extract_coefs(readRDS("../data/global_vollenweider.rds"), "k"), 
  extract_coefs2(readRDS("../data/lc_vollenweider.rds"), 
                 c("k1_lc", "k2_lc")),
  extract_coefs2(readRDS("../data/nws/cd_vollenweider.rds"), 
                 c("k1_cd", "k2_cd")),
  extract_coefs2(readRDS("../data/nws/ll_vollenweider.rds"), 
                 c("k1_ll", "k2_ll")),
  extract_coefs2(readRDS("../data/nws/la_vollenweider.rds"), 
                 c("k1_la", "k2_la")),
  extract_coefs2(readRDS("../data/nws/la_vollenweider.rds"), 
                 c("k1_la", "k2_la")),
  extract_coefs2(readRDS("../data/md_vollenweider.rds"), 
                 c("k1_md", "k2_md")),
  extract_coefs2(readRDS("../data/nws/bf_vollenweider.rds"), 
                 c("k1_bf", "k2_bf")),
  extract_coefs2(readRDS("../data/nws/sd_vollenweider.rds"), 
                 c("k1_sd", "k2_sd")),
  extract_coefs2(readRDS("../data/nws/sr_vollenweider.rds"), 
                 c("k1_sr", "k2_sr")))

# align iws and nws panel rows
fit_df_nws <- dplyr::filter(fit_df_nws, fit_df_nws$key %in% fit_df_iws$key) 

fit_df_nws$key <- factor(fit_df_nws$key, levels = c("k",
                                                    "k1_sr", "k2_sr",
                                                    "k1_bf", "k2_bf",
                                                    "k2_md", "k1_md",
                                                    "k1_la", "k2_la",
                                                    "k2_lc", "k1_lc",
                                                    "k2_sd", "k1_sd",
                                                    "k1_cd", "k2_cd",
                                                    "k1_ll", "k2_ll"))
# k2  = higher metric value
# right = higher connectivity, purple

k_viz_nws <- ggplot(
  fit_df_nws, 
  aes(x = coef, y = key, fill = key, color = key)) + 
  geom_density_ridges(size = 0.1, scale = 0.7, rel_min_height = 0.01) + 
  geom_hline(yintercept = seq(1.8, 16.8, by = 2)) +
  scale_fill_manual(values = c("grey",
                               rep(c(viridis::viridis(1, begin = 0.5),
                                     viridis::viridis(1, begin = 0)), 8))) +
  scale_color_manual(values = c("grey", 
                               rep(c(viridis::viridis(1, begin = 0.5), 
                                     viridis::viridis(1, begin = 0)), 8))) +
  cowplot::theme_cowplot() + theme(axis.text = element_text(size = 9),
                                   axis.text.y = element_text(size = 8, 
                                                face = colorado(nws_labels$parameter)),
                                   axis.title = element_text(size = 10),
                               plot.title = element_text(size = 9, face = "bold", hjust = 0),
                                   axis.line.x = element_line(size = 1, 
                                                  colour = "black"),
                                   axis.line.y = element_line(size = 1, 
                                                  colour = "black"), 
                                   legend.position = "none", 
                                   plot.margin = margin(0.5,0,0,-0.7, "cm")) + 
  xlab("k Value") +  ylab("") +
  scale_y_discrete(breaks = levels(fit_df_nws$key)[
    c(1, seq(3, length(levels(fit_df_nws$key)), by = 2))], 
    labels = nws_labels$parameter)

k_viz_nws

plot_grid(
  k_viz_iws + ggtitle("a. Lake Watershed") + xlim(0.8, 1.6),
  k_viz_nws + ggtitle("b. Lake Network Watershed") + xlim(0.8, 1.6), 
  ncol = 2, align = "v", rel_widths = c(1, 1)) + 
  theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"))

```
