---
title: "Figures"
output:
  pdf_document:
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
```

```{r read_chunks, cache=FALSE, echo=FALSE}
# knitr::read_chunk("../scripts/03_viz.R")
knitr::read_chunk("../scripts/99_utils.R")
```

```{r source_utils, message=FALSE, results='hide', echo=FALSE, warning=FALSE}

```

```{r load_data, message=FALSE, results='hide', echo=FALSE, warning=FALSE}
  source("../scripts/01.5_loaddata.R")
```

```{r 08_maps, echo=FALSE, fig.cap="Maps showing the locations of lake connectivity partitions. Green symbols indicate the lower of the two partition groups while purple symbols represent the higher of the two partition groups (see Table 2).", warning=FALSE, message=FALSE}

# ---- 08_maps ----

nes_sf    <- coordinatize(nes_nws, "lat", "long")
us_states <- st_intersects(us_states(), nes_sf)
us_states <- us_states()[unlist(lapply(us_states, function(x) length(x) > 0)),]

partition_splits <- read.csv("../figures/table_1.csv")
partition_splits <- dplyr::filter(partition_splits, !is.na(splits), 
                                  scale %in% c("nws", "iws"))
partition_splits <- droplevels(partition_splits)
partition_splits$pnames2 <- factor(partition_splits$pnames2, 
                              levels = c("cd", "ll", "la", "sd", "bf", "sr"))

metric_order_key <- data.frame(
  pnames2 = c("sr", "bf", "la", "sd", "cd", "ll"), 
  higher_connectivity = c("higher", "higher", "higher", "lower", "higher", "higher"))

partition_splits <- left_join(partition_splits, metric_order_key)

# pull the lower partition group as an sf object
lower_iws_maps <- lapply(which(partition_splits$scale == "iws"), 
                         function(x) {
                           # x <- which(partition_splits$scale == "iws")[3]
                           nes_sub <- get_sub(nes_iws, 
                                          partition_splits[x, "iws_names"],
                                          partition_splits[x, "splits"], 
                                          partition_splits[x, "higher_connectivity"])
                           
                           ggplot() + 
                             geom_sf(data = us_states) +
                             geom_sf(data = nes_sf, 
                                     color = viridis::viridis(1, begin = 0),
                                     size = 0.6) + 
                             geom_sf(data = nes_sub, 
                                color = viridis::viridis(1, begin = 0.5), 
                                size = 0.6) + 
                             coord_sf(datum = NA) + 
                             ggtitle(break_word(partition_splits[x, "abb"], 12)) + 
                             theme(plot.margin = unit(c(0, -0.1, 0, -0.1), "cm"),
                               plot.title = element_text(face = "plain", size = 12))
                         })

lower_nws_maps <- lapply(which(partition_splits$scale == "nws"), 
                         function(x) {
                           # x <- which(partition_splits$scale == "nws")[1]
                           nes_sub <- get_sub(nes_nws, 
                                          partition_splits[x, "nws_names"],
                                          partition_splits[x, "splits"], 
                                          partition_splits[x, "higher_connectivity"])
                           
                           nes_sf_temp <- nes_sf
                           st_geometry(nes_sf_temp) <- NULL
                           na_rows <- !is.na(
                    nes_sf_temp[,as.character(partition_splits[x, "nws_names"])])
                           
                           ggplot() + 
                             geom_sf(data = us_states) +
                             geom_sf(data = nes_sf, 
                                     color = viridis::viridis(1, begin = 0),
                                     size = 0.6) + 
                             geom_sf(data = nes_sub,
                                     color = viridis::viridis(1, begin = 0.5), 
                                     size = 0.6) + 
                             coord_sf(datum = NA) + 
                             ggtitle(break_word(partition_splits[x, "abb"], 12)) + 
                             theme(plot.margin = unit(c(0, -0.1, 0, -0.1), "cm"), 
                               plot.title = element_text(face = "plain", size  = 12))
                         })

partition_splits$pnames2 <- factor(partition_splits$pnames2, 
                                   levels = c("ll", "cd", "sd", "la", "bf", "sr"))

lower_iws_maps <- lower_iws_maps[
  match(levels(partition_splits$pnames2), 
        partition_splits$pnames2[which(partition_splits$scale == "iws")])
  ]

# lower_iws_maps[1][[1]] <- lower_iws_maps[1][[1]] + 
#   theme(plot.margin = unit(c(1,0,0,0), "lines"))

lower_nws_maps <- lower_nws_maps[
  match(levels(partition_splits$pnames2), 
        partition_splits$pnames2[which(partition_splits$scale == "nws")])
  ]

plot_grid(
  plot_grid(NULL,
            NULL, 
            NULL,
            NULL,
            NULL, 
            nrow = 4, ncol = 1,
            labels = c("A. LWS", "", "B. NWS", "", ""), 
            label_colour = "black", vjust = c(1.2, 0, 2, 0, 0), 
            hjust = c(-0.1, 0, -0.12, 0, 0)),
  plot_grid(
    plot_grid(plotlist = lower_iws_maps, 
                   ncol = 3, nrow = 2, align = "v"),
    plot_grid(ggplot() + geom_blank()),
    plot_grid(plotlist = lower_nws_maps,
                   ncol = 3, nrow = 2, align = "v"), 
    ncol = 1, rel_heights = c(1, 0.1, 1)), 
rel_widths = c(0.2, 1), ncol = 2)
```
